blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/mad-maids/maid.discussion/discussions
    about: Ask questions and post ideas
  - name: 💭 Discord Server
    url: https://discord.gg/mKKekABEzx
    about: Ask casual questions here
